# Generated by Django 2.0.5 on 2018-11-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givertransaction',
            name='amount',
            field=models.CharField(max_length=50),
        ),
    ]
