# Generated by Django 2.0.5 on 2018-11-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_alert', '0002_auto_20181102_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givertransaction',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
