# Generated by Django 2.0.5 on 2018-11-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_alert', '0003_auto_20181102_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='givertransaction',
            name='countone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
